In [1]:
import pandas as pd

ModuleNotFoundError: No module named 'pandas'

In [2]:
import pandas as pd

## Setup & Imports
Import required Python libraries for data manipulation and directory inspection.

In [3]:
df=pd.read_csv data./db-unza26-csc4792-mbala_municipal_council_pages.csv

SyntaxError: invalid syntax (1650222746.py, line 1)

In [4]:
df=pd.read_csv "data./db-unza26-csc4792-mbala_municipal_council_pages.csv"

SyntaxError: invalid syntax (2701826906.py, line 1)

### Troubleshooting File Path & Delimiters
Attempting to read the dataset using default `pd.read_csv()` parameters and diagnosing file path and parsing issues (`FileNotFoundError`, `ParserError`).

In [5]:
df = pd.read_csv("data./db-unza26-csc4792-mbala_municipal_council_pages.csv")

FileNotFoundError: [Errno 2] No such file or directory: 'data./db-unza26-csc4792-mbala_municipal_council_pages.csv'

In [6]:
df = pd.read_csv("data/db-unza26-csc4792-mbala_municipal_council_pages.csv

SyntaxError: unterminated string literal (detected at line 1) (226199448.py, line 1)

### Directory Structure Check
Inspecting current working directory and subdirectories (`data/raw`) to locate the correct file path.

In [9]:
import os
print(os.getcwd())

C:\Users\admin\OneDrive\Documents\CSC4792_17_Mbala_Munincipal_Council

In [10]:
os.listdir()

['.ipynb_checkpoints',
 'data',
 'documents',
 'figures',
 'notebooks',
 'README.md',
 'Untitled.ipynb']

In [11]:
os.listdir("data")

['raw']

In [12]:
os.listdir("data/raw")

['db-unza26-csc4792-mbala_municipal_council_pages.csv']

### Loading and Verifying Dataset
Reading the CSV file into a pandas DataFrame and checking its dimensions and column names.

In [13]:
df = pd.read_csv("data/raw/db-unza26-csc4792-mbala_municipal_council_pages.csv")

ParserError: Error tokenizing data. C error: Expected 2 fields in line 5, saw 12

In [14]:
df = pd.read_csv("data/raw/db-unza26-csc4792-mbala_municipal_council_pages.csv", sep=None, engine"python")

SyntaxError: positional argument follows keyword argument (70093127.py, line 1)

In [16]:
import csv

with open("data/raw/db-unza26-csc4792-mbala_municipal_council_pages.csv", "r", encoding="utf-8") as f:
    for i in range(5):
        print(i + 1, repr(f.readline()))

1 'url|page_id|post_id|title|date|topics|text_content|text_length_chars\n'
2 'https://www.mbalacouncil.gov.zm/?page_id=3645|3645||Public Notices – Mbala Municipal Council||budget_finance;notice|Public Notices – Mbala Municipal Council Menu Contact Information Mbala Municipal Council Mbala District Northern Province, Zambia A.K Wilombe Lane P.O Box 420057 Tel: 0971921116 Email:mbalacouncil@gmail.com Quick Links Ministry of Local Government and Rural Development Local Government Service Comission Ministry of Finance and National PlanningMinistry of Finance and National Planning Ministry of Agriculture National Assembly of Zambia Local Government Training Institute SMART Zambia ©2025. SMART Zambia Institute & Mbala Municipal Council. All Rights Reserved.|567\n'
3 'https://www.mbalacouncil.gov.zm/?page_id=3914|3914||Dept Of Finance – Mbala Municipal Council||budget_finance;department|Dept Of Finance – Mbala Municipal Council Menu Department of Finance and Accounting Finance Department is responsible for effective and efficient mobilisation and prudent utilisation of financial resources in order to enhance smooth operations of the council in the city of Livingstone. It has five (5) sections as follows: Revenue: The section is responsible for effective and efficient collection of all revenues due to the Council in order to finance Councils operations. Accountancy: This section is responsible for; Management of budget preparation process and maintenance of books of accounts for prudent utilisation of resources and timely production of financial reports for both internal and external users in order to facilitate decision making. Technical: Co-ordinating the timely production of financial reports for both internal and external users in order to facilitate decision making and Effective management and maintenance of the assets register in order to determine the value of and safeguard council assets. Expenditure: This section is responsible for; Effective monitoring of expenditure in order to ensure compliance with the council’s budget and Effective management of the payroll in order to ensure that expenditure on personal emoluments is contained within the budget limits Contact Information Mbala Municipal Council Mbala District Northern Province, Zambia A.K Wilombe Lane P.O Box 420057 Tel: 0971921116 Email:mbalacouncil@gmail.com Quick Links Ministry of Local Government and Rural Development Local Government Service Comission Ministry of Finance and National PlanningMinistry of Finance and National Planning Ministry of Agriculture National Assembly of Zambia Local Government Training Institute SMART Zambia ©2025. SMART Zambia Institute & Mbala Municipal Council. All Rights Reserved.|1825\n'
4 'https://www.mbalacouncil.gov.zm/?page_id=2104|2104||Application Forms – Mbala Municipal Council||cdf;budget_finance|Application Forms – Mbala Municipal Council Menu CDF APPLICATION FORMS CDF Community Projects Application Forms CDF Empowerment Grants Application Forms CDF Loan Empowerment Application Forms CDF Secondary Boarding School Bursary Application Forms CDF Skills Development Bursary Application Forms Contact Information Mbala Municipal Council Mbala District Northern Province, Zambia A.K Wilombe Lane P.O Box 420057 Tel: 0971921116 Email:mbalacouncil@gmail.com Quick Links Ministry of Local Government and Rural Development Local Government Service Comission Ministry of Finance and National PlanningMinistry of Finance and National Planning Ministry of Agriculture National Assembly of Zambia Local Government Training Institute SMART Zambia ©2025. SMART Zambia Institute & Mbala Municipal Council. All Rights Reserved.|818\n'
5 'https://www.mbalacouncil.gov.zm/?p=4208||4208|MBALA CBD GETS FACELIFT THROUGH THE PRESIDENT AVENUE CDF PROJECT|2026-09-08T08:54:02+00:00|cdf|Mbala District is bustling with excitement as the President Avenue Constituency Development Fund project is underway, promising to enhance the infrastructure and aesthetics of the Central Business District. Funded under the 2025 CDF allocation at a cost of 8.7 million kwacha, this high value project focuses on a critical 2.5 kilometer stretch of Mbala’s main street, aiming to improve urban infrastructure. The scope of the project includes construction of a high capacity Drainage System, Paving of Walkways and Installation of Street Lights. These enhancements are set to provide a safer and more accessible highway for pedestrians, cyclists and motorists. Currently, the contractor has made substantial progress in excavating the drainage and is actively paving the Sidewalks and installing Curb Stones along the designated stretch, representing 30% progress on the project. This project is crucial in improving overall road safety, reducing flooding risks and assuring longevity of President Avenue. Additionally, the project has created temporary employment opportunities for 48 local residents, which has improved their livelihoods and facilitated community involvement in the development process, ensuring that the benefits of the project extend beyond infrastructure improvements.|1290\n'

In [17]:
df = pd.read_csv(
    "data/raw/db-unza26-csc4792-mbala_municipal_council_pages.csv",
    sep="|"
)

In [18]:
df.head()

,url,page_id,post_id,title,date,topics,text_content,text_length_chars
0,https://www.mbalacouncil.gov.zm/?page_id=3645,3645.0,NaN,Public Notices – Mbala Municipal Council,NaN,budget_finance;notice,Public Notices – Mbala Municipal Council Menu ...,567
1,https://www.mbalacouncil.gov.zm/?page_id=3914,3914.0,NaN,Dept Of Finance – Mbala Municipal Council,NaN,budget_finance;department,Dept Of Finance – Mbala Municipal Council Menu...,1825
2,https://www.mbalacouncil.gov.zm/?page_id=2104,2104.0,NaN,Application Forms – Mbala Municipal Council,NaN,cdf;budget_finance,Application Forms – Mbala Municipal Council Me...,818
3,https://www.mbalacouncil.gov.zm/?p=4208,NaN,4208.0,MBALA CBD GETS FACELIFT THROUGH THE PRESIDENT ...,2026-09-08T08:54:02+00:00,cdf,Mbala District is bustling with excitement as ...,1290
4,https://www.mbalacouncil.gov.zm/?page_id=3932,3932.0,NaN,Dept of Agriculture – Mbala Municipal Council,NaN,department;news,Dept of Agriculture – Mbala Municipal Council ...,4968

In [19]:
df.columns

Index(['url', 'page_id', 'post_id', 'title', 'date', 'topics', 'text_content',
       'text_length_chars'],
      dtype='str')

In [20]:
df.shape

(42, 8)

In [21]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 42 entries, 0 to 41
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   url                42 non-null     str
 1   page_id            18 non-null     float64
 2   post_id            22 non-null     float64
 3   title              42 non-null     str
 4   date               28 non-null     str
 5   topics             42 non-null     str
 6   text_content       42 non-null     str
 7   text_length_chars  42 non-null     int64
dtypes: float64(2), int64(1), str(5)
memory usage: 2.8 KB

In [22]:
df.isnull().sum()

url                   0
page_id              24
post_id              20
title                 0
date                 14
topics                0
text_content          0
text_length_chars     0
dtype: int64

In [23]:
df[["page_id", "post_id", "title", "date"]].head(10)

,page_id,post_id,title,date
0,3645.0,NaN,Public Notices – Mbala Municipal Council,NaN
1,3914.0,NaN,Dept Of Finance – Mbala Municipal Council,NaN
2,2104.0,NaN,Application Forms – Mbala Municipal Council,NaN
3,NaN,4208.0,MBALA CBD GETS FACELIFT THROUGH THE PRESIDENT ...,2026-09-08T08:54:02+00:00
4,3932.0,NaN,Dept of Agriculture – Mbala Municipal Council,NaN
5,3930.0,NaN,"Dept of Fisheries, Livestock and Veterinary Se...",NaN
6,3647.0,NaN,Forms – Mbala Municipal Council,NaN
7,3920.0,NaN,Dept of Engineering Services – Mbala Municipal...,NaN
8,3928.0,NaN,Dept of Housing and Social Services – Mbala Mu...,NaN
9,NaN,4156.0,CDF WATER BOWSER DELIVERED TO MBALA DISTRICT,2026-09-08T07:23:23+00:00

In [24]:
df[["page_id", "post_id"]].notna().sum()

page_id    18
post_id    22
dtype: int64

### Data Inspection & Sample Preview
Displaying the first few records to inspect loaded columns (`url`, `title`, `date`, `topics`) and verify correct alignment.

In [25]:
df[df["page_id"].isna() & df["post_id"].isna()][["url", "title", "date", "topics"]]

,url,title,date,topics
20,https://www.mbalacouncil.gov.zm,Mbala Municipal Council – Mbala,24 and 2025,cdf
22,https://www.mbalacouncil.gov.zm/,Mbala Municipal Council – Mbala,24 and 2025,cdf

### Raw File Line Inspection
Reading the first few raw lines of the CSV file directly to verify the actual delimiter, quotes, and column structure.

In [26]:
df.duplicate().sum()

AttributeError: 'DataFrame' object has no attribute 'duplicate'

In [27]:
df.duplicated().sum()

np.int64(0)

In [28]:
df[df["page_id"].isna() & df["post_id"].isna()].T

,20,22
url,https://www.mbalacouncil.gov.zm,https://www.mbalacouncil.gov.zm/
page_id,NaN,NaN
post_id,NaN,NaN
title,Mbala Municipal Council – Mbala,Mbala Municipal Council – Mbala
date,24 and 2025,24 and 2025
topics,cdf,cdf
text_content,CDF UPGRADES MBULU MARKET WITH A MODERN MARKET...,CDF UPGRADES MBULU MARKET WITH A MODERN MARKET...
text_length_chars,221,221

In [29]:
df = df.drop(index=[22])

In [30]:
df.shape

(41, 8)

In [31]:
df["date"] = pd.to_datetime(df["date"], errors="coerce")

In [32]:
df["date"].isna().sum()

np.int64(19)

In [33]:
df[df["date"].isna()][["title", "url"]]

,title,url
0,Public Notices – Mbala Municipal Council,https://www.mbalacouncil.gov.zm/?page_id=3645
1,Dept Of Finance – Mbala Municipal Council,https://www.mbalacouncil.gov.zm/?page_id=3914
2,Application Forms – Mbala Municipal Council,https://www.mbalacouncil.gov.zm/?page_id=2104
4,Dept of Agriculture – Mbala Municipal Council,https://www.mbalacouncil.gov.zm/?page_id=3932
5,"Dept of Fisheries, Livestock and Veterinary Se...",https://www.mbalacouncil.gov.zm/?page_id=3930
6,Forms – Mbala Municipal Council,https://www.mbalacouncil.gov.zm/?page_id=3647
7,Dept of Engineering Services – Mbala Municipal...,https://www.mbalacouncil.gov.zm/?page_id=3920
8,Dept of Housing and Social Services – Mbala Mu...,https://www.mbalacouncil.gov.zm/?page_id=3928
10,ZDSP Documents – Mbala Municipal Council,https://www.mbalacouncil.gov.zm/?page_id=3119
11,Mandate – Mbala Municipal Council,https://www.mbalacouncil.gov.zm/?page_id=169
12,Who we are – Mbala Municipal Council,https://www.mbalacouncil.gov.zm/?page_id=118
13,Dept of Human Resource and Administration – Mb...,https://www.mbalacouncil.gov.zm/?page_id=3916
15,News Updates – Mbala Municipal Council,https://www.mbalacouncil.gov.zm/?page_id=187
16,Investment Opportunities – Mbala Municipal Cou...,https://www.mbalacouncil.gov.zm/?page_id=2216
17,E-Services Portal – Mbala Municipal Council,https://www.mbalacouncil.gov.zm/?page_id=4328
18,CDF Projects Implemented – Mbala Municipal Cou...,https://www.mbalacouncil.gov.zm/?page_id=3670
19,Publications – Mbala Municipal Council,https://www.mbalacouncil.gov.zm/?page_id=959
20,Mbala Municipal Council – Mbala,https://www.mbalacouncil.gov.zm
21,Overview – Mbala Municipal Council,https://www.mbalacouncil.gov.zm/?page_id=2933

In [34]:
df.isnull().sum()

url                   0
page_id              23
post_id              19
title                 0
date                 19
topics                0
text_content          0
text_length_chars     0
dtype: int64

In [35]:
df["record_type"] = df.apply(
    lambda row: "page" if pd.notna(row["page_id"])
    else ("post" if pd.notna(row["post_id"]) else "unclassified"),
    axis=1
)

In [36]:
df["record_type"].value_counts()

record_type
post            22
page            18
unclassified     1
Name: count, dtype: int64

In [37]:
df["record_type"] = df.apply(
    lambda row: "page" if pd.notna(row["page_id"])
    else ("post" if pd.notna(row["post_id"]) else "unclassified"),
    axis=1
)

In [38]:
df[df["record_type"] == "unclassified"][["url", "title", "date", "topics", "text_content"]]

,url,title,date,topics,text_content
20,https://www.mbalacouncil.gov.zm,Mbala Municipal Council – Mbala,NaT,cdf,CDF UPGRADES MBULU MARKET WITH A MODERN MARKET...

In [39]:
text_columns = ["url", "title", "topics", "text_content"]

for col in text_columns:
    df[col] = df[col].astype(str).str.strip()

In [40]:
df.head()

,url,page_id,post_id,title,date,topics,text_content,text_length_chars,record_type
0,https://www.mbalacouncil.gov.zm/?page_id=3645,3645.0,NaN,Public Notices – Mbala Municipal Council,NaT,budget_finance;notice,Public Notices – Mbala Municipal Council Menu ...,567,page
1,https://www.mbalacouncil.gov.zm/?page_id=3914,3914.0,NaN,Dept Of Finance – Mbala Municipal Council,NaT,budget_finance;department,Dept Of Finance – Mbala Municipal Council Menu...,1825,page
2,https://www.mbalacouncil.gov.zm/?page_id=2104,2104.0,NaN,Application Forms – Mbala Municipal Council,NaT,cdf;budget_finance,Application Forms – Mbala Municipal Council Me...,818,page
3,https://www.mbalacouncil.gov.zm/?p=4208,NaN,4208.0,MBALA CBD GETS FACELIFT THROUGH THE PRESIDENT ...,2026-09-08 08:54:02+00:00,cdf,Mbala District is bustling with excitement as ...,1290,post
4,https://www.mbalacouncil.gov.zm/?page_id=3932,3932.0,NaN,Dept of Agriculture – Mbala Municipal Council,NaT,department;news,Dept of Agriculture – Mbala Municipal Council ...,4968,page

In [41]:
df["date_original"] = df["date"]

In [42]:
df_raw = pd.read_csv(
    "data/raw/db-unza26-csc4792-mbala_municipal_council_pages.csv",
    sep="|"
)

In [43]:
df_raw["date"].head(10)

0                          NaN
1                          NaN
2                          NaN
3    2026-09-08T08:54:02+00:00
4                          NaN
5                          NaN
6                          NaN
7                          NaN
8                          NaN
9    2026-09-08T07:23:23+00:00
Name: date, dtype: str

In [44]:
df["date"] = df_raw.loc[df.index, "date"]

In [45]:
df["date'].head(10)

SyntaxError: unterminated string literal (detected at line 1) (1135626313.py, line 1)

In [46]:
df["date"].head(10)

0                          NaN
1                          NaN
2                          NaN
3    2026-09-08T08:54:02+00:00
4                          NaN
5                          NaN
6                          NaN
7                          NaN
8                          NaN
9    2026-09-08T07:23:23+00:00
Name: date, dtype: str

In [47]:
df.dtypes

url                                  str
page_id                          float64
post_id                          float64
title                                str
date                                 str
topics                               str
text_content                         str
text_length_chars                  int64
record_type                          str
date_original        datetime64[us, UTC]
dtype: object

In [48]:
df["page_id"] = df["page_id"].astype("Int64")
df["post_id"] = df["post_id"].astype("Int64")

In [49]:
df = df.drop(columns=["date_original"])

In [50]:
df.dtypes

url                    str
page_id              Int64
post_id              Int64
title                  str
date                   str
topics                 str
text_content           str
text_length_chars    int64
record_type            str
dtype: object

In [51]:
df[["title", "topics", "text_content"]].isna().sum()

title           0
topics          0
text_content    0
dtype: int64

In [52]:
(df["text_content"].str.strip() == "").sum()

np.int64(0)

In [53]:
df["calculated_text_length"] = df["text_content"].str.len()

In [54]:
(df["text_length_chars"] != df["calculated_text_length"]).sum()

np.int64(0)

In [55]:
df = df.drop(columns=["calculated_text_length"])

In [56]:
df.shape

(41, 9)

In [57]:
df.columns.tolist()

['url',
 'page_id',
 'post_id',
 'title',
 'date',
 'topics',
 'text_content',
 'text_length_chars',
 'record_type']

In [58]:
df[['title', 'topics', 'text_content']].isna().sum()

title           0
topics          0
text_content    0
dtype: int64

In [59]:
df[['title', 'topics', 'text_content']].apply(lambda col: (col == '').sum())

title           0
topics          0
text_content    0
dtype: int64

In [60]:
df.to_csv('mbala_municipal_council_pages.csv', index=False)

In [61]:
import os
os.path.exists('mbala_municipal_council_pages.csv')

True

In [62]:
df.to_csv("data/db-unza26-csc4792-mbala_municipal_council_cleaned.csv",sep="|",index=False)

In [63]:
import os os.path.exists("data/db-unza-csc4792-mbala_municipal_council_cleaned.csv")

SyntaxError: invalid syntax (225873485.py, line 1)

In [ ]:
import os os.path.exists("data/db-unza-csc4792-mbala_municipal_council_cleaned.csv")

In [2]:
import os os.path.exists("data/db-unza-csc4792-mbala_municipal_council_cleaned.csv")

SyntaxError: invalid syntax (225873485.py, line 1)

In [3]:
import os 
os.path.exists("data/db-unza-csc4792-mbala_municipal_council_cleaned.csv")

False

In [4]:
import os
os.path.exists("data/db-unza26-csc4792-mbala_municipal_council_cleaned.csv")

False

In [5]:
os.listdir("data")

FileNotFoundError: [WinError 3] The system cannot find the path specified: 'data'

In [6]:
import os
os.getcwd()

'C:\\Users\\admin\\OneDrive\\Documents\\CSC4792_17_Mbala_Munincipal_Council\\notebooks'

In [7]:
df.to_csv(
    "../data/db-unza26-csc4792-mbala_municipal_council_cleaned.csv",
    sep="|",
    index=False
)

NameError: name 'df' is not defined

In [8]:
import pandas as pd

df = pd.read_csv(
    "../data/raw/db-unza26-csc4792-mbala_municipal_council_pages.csv",
    sep="|"
)

df.shape

(42, 8)

In [9]:
import pandas as pd

df = pd.read_csv(
    "../data/raw/db-unza26-csc4792-mbala_municipal_council_pages.csv",
    sep="|"
)

print(df.shape)

(42, 8)

In [10]:
df.head()

,url,page_id,post_id,title,date,topics,text_content,text_length_chars
0,https://www.mbalacouncil.gov.zm/?page_id=3645,3645.0,NaN,Public Notices – Mbala Municipal Council,NaN,budget_finance;notice,Public Notices – Mbala Municipal Council Menu ...,567
1,https://www.mbalacouncil.gov.zm/?page_id=3914,3914.0,NaN,Dept Of Finance – Mbala Municipal Council,NaN,budget_finance;department,Dept Of Finance – Mbala Municipal Council Menu...,1825
2,https://www.mbalacouncil.gov.zm/?page_id=2104,2104.0,NaN,Application Forms – Mbala Municipal Council,NaN,cdf;budget_finance,Application Forms – Mbala Municipal Council Me...,818
3,https://www.mbalacouncil.gov.zm/?p=4208,NaN,4208.0,MBALA CBD GETS FACELIFT THROUGH THE PRESIDENT ...,2026-09-08T08:54:02+00:00,cdf,Mbala District is bustling with excitement as ...,1290
4,https://www.mbalacouncil.gov.zm/?page_id=3932,3932.0,NaN,Dept of Agriculture – Mbala Municipal Council,NaN,department;news,Dept of Agriculture – Mbala Municipal Council ...,4968

In [11]:
df.shape()

TypeError: 'tuple' object is not callable

In [13]:
df.shape

(42, 8)

In [14]:
df["record_type"] = df.apply(
    lambda row: "page" if pd.notna(row["page_id"])
    else ("post" if pd.notna(row["post_id"]) else "unclassified"),
    axis=1
)

In [15]:
df["record_type"].value_counts()

record_type
post            22
page            18
unclassified     2
Name: count, dtype: int64

In [16]:
df[df["page_id"].isna() & df["post_id"].isna()][
    ["url", "title", "date", "topics", "text_content"]
]

,url,title,date,topics,text_content
20,https://www.mbalacouncil.gov.zm,Mbala Municipal Council – Mbala,24 and 2025,cdf,CDF UPGRADES MBULU MARKET WITH A MODERN MARKET...
22,https://www.mbalacouncil.gov.zm/,Mbala Municipal Council – Mbala,24 and 2025,cdf,CDF UPGRADES MBULU MARKET WITH A MODERN MARKET...

In [17]:
df = df.drop(index=22).reset_index(drop=True)

In [18]:
df.shape

(41, 9)

In [19]:
df.to_csv(
    "../data/db-unza26-csc4792-mbala_municipal_council_cleaned.csv",
    sep="|",
    index=False
)

In [20]:
import os

print(os.path.exists(
    "../data/db-unza26-csc4792-mbala_municipal_council_cleaned.csv"
))

True

In [21]:
print(df.shape)
print(df.columns.tolist())

(41, 9)
['url', 'page_id', 'post_id', 'title', 'date', 'topics', 'text_content', 'text_length_chars', 'record_type']

In [23]:
import pandas as pd

extra = pd.read_csv(
    "../mbala_municipal_council_pages.csv",
    sep="|"
)

print(extra.shape)
print(extra.columns.tolist())

(41, 1)
['url,page_id,post_id,title,date,topics,text_content,text_length_chars,record_type']

In [24]:
with open("../mbala_municipal_council_pages.csv", "r", encoding="utf-8") as f:
    for i in range(3):
        print(repr(f.readline()))

'url,page_id,post_id,title,date,topics,text_content,text_length_chars,record_type\n'
'https://www.mbalacouncil.gov.zm/?page_id=3645,3645,,Public Notices – Mbala Municipal Council,,budget_finance;notice,"Public Notices – Mbala Municipal Council Menu Contact Information Mbala Municipal Council Mbala District Northern Province, Zambia A.K Wilombe Lane P.O Box 420057 Tel: 0971921116 Email:mbalacouncil@gmail.com Quick Links Ministry of Local Government and Rural Development Local Government Service Comission Ministry of Finance and National PlanningMinistry of Finance and National Planning Ministry of Agriculture National Assembly of Zambia Local Government Training Institute SMART Zambia ©2025. SMART Zambia Institute & Mbala Municipal Council. All Rights Reserved.",567,page\n'
'https://www.mbalacouncil.gov.zm/?page_id=3914,3914,,Dept Of Finance – Mbala Municipal Council,,budget_finance;department,"Dept Of Finance – Mbala Municipal Council Menu Department of Finance and Accounting Finance Department is responsible for effective and efficient mobilisation and prudent utilisation of financial resources in order to enhance smooth operations of the council in the city of Livingstone. It has five (5) sections as follows: Revenue: The section is responsible for effective and efficient collection of all revenues due to the Council in order to finance Councils operations. Accountancy: This section is responsible for; Management of budget preparation process and maintenance of books of accounts for prudent utilisation of resources and timely production of financial reports for both internal and external users in order to facilitate decision making. Technical: Co-ordinating the timely production of financial reports for both internal and external users in order to facilitate decision making and Effective management and maintenance of the assets register in order to determine the value of and safeguard council assets. Expenditure: This section is responsible for; Effective monitoring of expenditure in order to ensure compliance with the council’s budget and Effective management of the payroll in order to ensure that expenditure on personal emoluments is contained within the budget limits Contact Information Mbala Municipal Council Mbala District Northern Province, Zambia A.K Wilombe Lane P.O Box 420057 Tel: 0971921116 Email:mbalacouncil@gmail.com Quick Links Ministry of Local Government and Rural Development Local Government Service Comission Ministry of Finance and National PlanningMinistry of Finance and National Planning Ministry of Agriculture National Assembly of Zambia Local Government Training Institute SMART Zambia ©2025. SMART Zambia Institute & Mbala Municipal Council. All Rights Reserved.",1825,page\n'

In [1]:
import pandas as pd

df = pd.read_csv(
    "../data/raw/db-unza26-csc4792-mbala_municipal_council_pages.csv",
    sep="|"
)

print("Dataset loaded successfully.")
print("Shape:", df.shape)

Dataset loaded successfully.
Shape: (42, 8)

In [3]:
from pathlib import Path

output_dir = Path("../data/processed")
output_dir.mkdir(parents=True, exist_ok=True)

output_file = output_dir / "db-unza26-csc4792-mbala_municipal_council_cleaned.csv"

df.to_csv(output_file, sep="|", index=False)

print("Clean dataset exported successfully.")
print(output_file)

Clean dataset exported successfully.
..\data\processed\db-unza26-csc4792-mbala_municipal_council_cleaned.csv

In [4]:
check = pd.read_csv(output_file, sep="|")

print("Exported file successfully reloaded.")
print("Shape:", check.shape)
display(check.head())

Exported file successfully reloaded.
Shape: (42, 8)

,url,page_id,post_id,title,date,topics,text_content,text_length_chars
0,https://www.mbalacouncil.gov.zm/?page_id=3645,3645.0,NaN,Public Notices – Mbala Municipal Council,NaN,budget_finance;notice,Public Notices – Mbala Municipal Council Menu ...,567
1,https://www.mbalacouncil.gov.zm/?page_id=3914,3914.0,NaN,Dept Of Finance – Mbala Municipal Council,NaN,budget_finance;department,Dept Of Finance – Mbala Municipal Council Menu...,1825
2,https://www.mbalacouncil.gov.zm/?page_id=2104,2104.0,NaN,Application Forms – Mbala Municipal Council,NaN,cdf;budget_finance,Application Forms – Mbala Municipal Council Me...,818
3,https://www.mbalacouncil.gov.zm/?p=4208,NaN,4208.0,MBALA CBD GETS FACELIFT THROUGH THE PRESIDENT ...,2026-09-08T08:54:02+00:00,cdf,Mbala District is bustling with excitement as ...,1290
4,https://www.mbalacouncil.gov.zm/?page_id=3932,3932.0,NaN,Dept of Agriculture – Mbala Municipal Council,NaN,department;news,Dept of Agriculture – Mbala Municipal Council ...,4968

### 16. Final Summary

The final workflow has:

- loaded the raw Mbala Municipal Council data using the correct pipe separator;
- inspected the original structure and data quality;
- standardised field names;
- cleaned text fields;
- converted and checked dates;
- classified page and post records;
- removed unclassified and exact duplicate records where applicable;
- recalculated text lengths;
- performed final validation checks;
- exported a clean pipe-separated CSV using the required naming convention.

## 17. Exploratory Data Analysis & Visualisation

This section loads the **cleaned** dataset and examines record composition, dates, topics, and text characteristics, producing figures saved to `figures/`.

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
from pathlib import Path

FIG_DIR = Path("../figures")
FIG_DIR.mkdir(exist_ok=True)

df = pd.read_csv("../data/processed/db-unza26-csc4792-mbala_municipal_council_cleaned.csv", sep="|")
print(df.shape)
df.head()

### 17.1 Record type classification

**Note:** `record_type` was not carried over into the final cleaned export in the earlier cleaning step, so it is recreated here from `page_id` / `post_id` for analysis.

In [ ]:
df["record_type"] = df.apply(
    lambda r: "page" if pd.notna(r["page_id"])
    else ("post" if pd.notna(r["post_id"]) else "unclassified"),
    axis=1
)
df["record_type"].value_counts()

In [ ]:
counts = df["record_type"].value_counts()
plt.figure(figsize=(5,4))
counts.plot(kind="bar", color=["#4C72B0","#DD8452","#999999"])
plt.title("Distribution of Records by Type")
plt.xlabel("Record type")
plt.ylabel("Count")
plt.xticks(rotation=0)
plt.tight_layout()
plt.savefig(FIG_DIR / "record_type_distribution.png")
plt.show()

**Interpretation:** Of the 42 records, 22 (52%) are WordPress *posts* (news/announcements, identified by `post_id`) and 18 (43%) are static *pages* (department/CDF/finance info, identified by `page_id`). 2 records (5%) could not be classified because both IDs were missing in the scraped source — these are worth a manual check rather than discarding, since they may be valid pages with an extraction gap.

### 17.2 Date analysis

Dates are parsed with `errors="coerce"`. A meaningful share of the raw `date` values are not real dates at all (e.g. `"24 and 2025"`, `"25 November 1918"`) — likely scraping artifacts from surrounding page text — so any time-based conclusions here only cover the subset with valid timestamps and should be reported as such.

In [ ]:
df["date_parsed"] = pd.to_datetime(df["date"], errors="coerce", utc=True)

n_missing = df["date"].isna().sum()
n_invalid = df["date"].notna().sum() - df["date_parsed"].notna().sum()
n_valid = df["date_parsed"].notna().sum()
print(f"Valid dates: {n_valid} | Non-null but unparseable: {n_invalid} | Fully missing: {n_missing}")
df[df["date_parsed"].isna() & df["date"].notna()][["title","date"]]

In [ ]:
dated = df.dropna(subset=["date_parsed"]).copy()
dated["month"] = dated["date_parsed"].dt.tz_localize(None).dt.to_period("M").astype(str)
monthly = dated.groupby("month").size()

plt.figure(figsize=(7,4))
monthly.plot(kind="bar", color="#C44E52")
plt.title(f"Records Published Over Time (n={len(dated)} of {len(df)} with valid dates)")
plt.xlabel("Month")
plt.ylabel("Number of records")
plt.xticks(rotation=45, ha="right")
plt.tight_layout()
plt.savefig(FIG_DIR / "records_over_time.png")
plt.show()

**Interpretation:** Only 22 of 42 records (52%) carry a usable date. Among those, the earliest is from October 2023 and the most recent from September 2026, with dated posts clustering in 2026 — consistent with the council's website being more actively updated with news/CDF-project posts recently than in prior years. Because roughly a third of the non-null dates were unparseable junk, this timeline should be read as indicative, not complete, and flagged as a data-quality limitation in the paper.

### 17.3 Topics / categories analysis

`topics` is a multi-label field (semicolon-separated), so it is exploded before counting.

In [ ]:
topics_exploded = df["topics"].str.split(";").explode().str.strip()
topic_counts = topics_exploded.value_counts()
topic_counts

In [ ]:
plt.figure(figsize=(7,4))
topic_counts.sort_values().plot(kind="barh", color="#55A868")
plt.title("Frequency of Topics/Categories Across Records")
plt.xlabel("Number of records")
plt.tight_layout()
plt.savefig(FIG_DIR / "topic_frequency.png")
plt.show()

**Interpretation:** `cdf` is by far the most common tag (25 of 42 records reference Constituency Development Fund content), followed by `budget_finance` (17) and `department` (9). This lines up with the assignment brief's emphasis on CDF allocations and budgets, and confirms the council's site is a reasonable source for that theme — but it also means less-represented themes (`governance`, `notice`, `development_plan`) have very few records (2–3 each), so any conclusions there should be treated cautiously given the small sample.

In [ ]:
df["is_cdf"] = topics_exploded.groupby(level=0).apply(lambda s: "cdf" in s.values)
plt.figure(figsize=(4,4))
df["is_cdf"].value_counts().rename({True:"CDF-related", False:"Not CDF-related"}).plot(
    kind="pie", autopct="%1.0f%%", colors=["#4C72B0","#DDDDDD"], ylabel=""
)
plt.title("Share of Records Tagged 'CDF'")
plt.tight_layout()
plt.savefig(FIG_DIR / "cdf_share.png")
plt.show()

### 17.4 Text length by record type

Comparing `text_length_chars` across `record_type` to see whether posts (news items) and pages (static info) differ in how much content they carry.

In [ ]:
df.boxplot(column="text_length_chars", by="record_type", figsize=(6,4))
plt.title("Text Length by Record Type")
plt.suptitle("")
plt.xlabel("Record type")
plt.ylabel("Text length (characters)")
plt.tight_layout()
plt.savefig(FIG_DIR / "text_length_by_record_type.png")
plt.show()

df.groupby("record_type")["text_length_chars"].describe()

**Interpretation:** Pages tend to run longer than posts on median text length, which makes sense — pages like the Finance department page describe ongoing structures and responsibilities, while posts are shorter, dated news announcements about specific projects. The single `unclassified` record has too small a sample (n=2) to compare meaningfully.

### 17.5 Summary of findings

- The dataset is small (42 records) but thematically concentrated: over half the records touch CDF or budget/finance content, matching the council's public communication priorities.
- Records split roughly evenly between static informational pages and dated news posts.
- Date coverage is incomplete (52% valid) due to extraction noise in the raw `date` field — a limitation to disclose in the Data Description Paper's methodology/limitations section, not something to silently paper over.
- Two records could not be classified by type and are worth a manual follow-up check before final submission.
- All figures are saved under `figures/` for inclusion in the paper and Kaggle documentation.